name = "sdr-auto-rayr"
compatibility_date = "2026-04-17"
compatibility_flags = ["nodejs_compat"]
main = ".open-next/worker.js"
assets = { directory = ".open-next/assets" }

[observability]
enabled = true
